all:
	gcc -Wall -D tshell.c -o tshell

fork:
	gcc -Wall -D FORK tshell.c -o tshell

vfork:
	gcc -Wall -D VFORK tshell.c -o tshell

clone:
	gcc -Wall -D CLONE tshell.c -o tshell

fifo:
	gcc -Wall -D FIFO tshell.c -o tshell
